### ISSUE TITLE
Pushbutton

### ISSUE THREAD

**Issue by ThaneGallo** [ThaneGallo/ESP_MorseCode#2]
Read through push button sample code

Find how to print button value to console 
decide length of time to decide dot/dash 

attempt to store and decode values

**Comment by ThaneGallo** [comment]
https://docs.espressif.com/projects/esp-idf/en/v4.4.5/esp32s2/api-reference/peripherals/touch_element.html

**Comment by ThaneGallo** [comment]
^ honestly explains a lot (if we can get all of this compressed into a single function for the the main function that would be pretty pog) bc theres so much under the surface

**Comment by coop-bennett** [comment]
Button code written. Length determined. Caught out of bounds issues. No decode code written yet.
